buttons:
  - name: button1
    command: ls -lh
  - name: button2
    command: lsb_release -d
  - name: button3
    command: sensors -u
  - name: button4
    command: ps -ef
  - name: button5
    command: lsb_release -d
  - name: button6
    command: sensors -u
  - name: button7
    command: ls -lh
  - name: button8
    command: lsb_release -d
  - name: button9
    command: sensors -u
  - name: button10
    command: ls -lh
  - name: button11
    command: ls -lh
  - name: button12
    command: lsb_release -d
  - name: button13
    command: sensors -u
  - name: button14
    command: ls -lh
  - name: button15
    command: lsb_release -d
  - name: button16
    command: sensors -u
  - name: button17
    command: ls -lh
  - name: button18
    command: lsb_release -d
  - name: button19
    command: sensors -u
  - name: button20
    command: ls -lh
  - name: button21
    command: ls -lh
  - name: button22
    command: lsb_release -d
  - name: button23
    command: sensors -u
  - name: button24
    command: ls -lh
  - name: button25
    command: lsb_release -d
  - name: button26
    command: sensors -u
  - name: button27
    command: ls -lh
  - name: button28
    command: lsb_release -d
  - name: button29
    command: sensors -u
  - name: button30
    command: ls -lh
  - name: button31
    command: ls -lh
  - name: button32
    command: lsb_release -d
  - name: button33
    command: sensors -u
  - name: button34
    command: ls -lh
  - name: button35
    command: lsb_release -d
  - name: button36
    command: sensors -u
  - name: button37
    command: ls -lh
  - name: button38
    command: lsb_release -d
  - name: button39
    command: sensors -u
  - name: button40
    command: ls -lh
  - name: button41
    command: ls -lh
  - name: button42
    command: lsb_release -d
  - name: button43
    command: sensors -u
  - name: button44
    command: ls -lh
  - name: button45
    command: lsb_release -d
  - name: button46
    command: sensors -u
  - name: button47
    command: ls -lh
  - name: button48
    command: lsb_release -d
  - name: button49
    command: sensors -u
  - name: button50
    command: ls -lh
  - name: button51
    command: ls -lh
  - name: button52
    command: lsb_release -d
  - name: button53
    command: sensors -u
  - name: button54
    command: ls -lh
  - name: button55
    command: lsb_release -d
  - name: button56
    command: sensors -u
  - name: button57
    command: ls -lh
  - name: button58
    command: lsb_release -d
  - name: button59
    command: sensors -u
  - name: button60
    command: ls -lh
  - name: button61
    command: ls -lh
  - name: button62
    command: lsb_release -d
  - name: button63
    command: sensors -u
  - name: button64
    command: ls -lh
  - name: button65
    command: lsb_release -d
  - name: button66
    command: sensors -u
  - name: button67
    command: ls -lh
  - name: button68
    command: lsb_release -d
  - name: button69
    command: sensors -u
  - name: button70
    command: ls -lh
  - name: button71
    command: ls -lh
  - name: button72
    command: lsb_release -d
  - name: button73
    command: sensors -u
  - name: button74
    command: ls -lh
  - name: button75
    command: lsb_release -d
  - name: button76
    command: sensors -u
  - name: button77
    command: ls -lh
  - name: button78
    command: lsb_release -d
  - name: button79
    command: sensors -u
  - name: button80
    command: ls -lh
  - name: button81
    command: ls -lh
  - name: button82
    command: lsb_release -d
  - name: button83
    command: sensors -u
  - name: button84
    command: ls -lh
  - name: button85
    command: lsb_release -d
  - name: button86
    command: sensors -u
  - name: button87
    command: ls -lh
  - name: button88
    command: lsb_release -d
  - name: button89
    command: sensors -u
  - name: button90
    command: ls -lh
  - name: button91
    command: ls -lh
  - name: button92
    command: lsb_release -d
  - name: button93
    command: sensors -u
  - name: button94
    command: ls -lh
  - name: button95
    command: lsb_release -d
  - name: button96
    command: sensors -u
  - name: button97
    command: ls -lh
  - name: button98
    command: lsb_release -d
  - name: button99
    command: sensors -u
  - name: button100
    command: ls -lh
  - name: button101
    command: ls -lh
  - name: button102
    command: lsb_release -d
  - name: button103
    command: sensors -u
  - name: button104
    command: ls -lh
  - name: button105
    command: lsb_release -d
  - name: button106
    command: sensors -u
  - name: button107
    command: ls -lh
  - name: button108
    command: lsb_release -d
  - name: button109
    command: sensors -u
  - name: button110
    command: ls -lh
  - name: button111
    command: ls -lh
  - name: button112
    command: lsb_release -d
  - name: button113
    command: sensors -u
  - name: button114
    command: ls -lh
  - name: button115
    command: lsb_release -d
  - name: button116
    command: sensors -u
  - name: button117
    command: ls -lh
  - name: button18
    command: lsb_release -d
  - name: button119
    command: sensors -u
  - name: button120
    command: ls -lh
  - name: button121
    command: ls -lh
  - name: button122
    command: lsb_release -d
  - name: button123
    command: sensors -u
  - name: button124
    command: ls -lh
  - name: button125
    command: lsb_release -d
  - name: button126
    command: sensors -u
  - name: button127
    command: ls -lh
  - name: button128
    command: lsb_release -d
  - name: button129
    command: sensors -u
  - name: button130
    command: ls -lh
  - name: button131
    command: ls -lh
  - name: button132
    command: lsb_release -d
  - name: button133
    command: sensors -u
  - name: button134
    command: ls -lh
  - name: button135
    command: lsb_release -d
  - name: button136
    command: sensors -u
  - name: button137
    command: ls -lh
  - name: button138
    command: lsb_release -d
  - name: button139
    command: sensors -u
  - name: button140
    command: ls -lh
  - name: button141
    command: ls -lh
  - name: button142
    command: lsb_release -d
  - name: button143
    command: sensors -u
  - name: button144
    command: ls -lh
  - name: button145
    command: lsb_release -d
  - name: button146
    command: sensors -u
  - name: button147
    command: ls -lh
  - name: button148
    command: lsb_release -d
  - name: button149
    command: sensors -u
  - name: button150
    command: sensors -u
  - name: button151
    command: ls -lh
  - name: button152
    command: lsb_release -d
  - name: button153
    command: sensors -u
  - name: button154
    command: ls -lh
  - name: button155
    command: lsb_release -d
  - name: button156
    command: sensors -u
  - name: button157
    command: ls -lh
  - name: button158
    command: lsb_release -d
  - name: button159
    command: sensors -u
  - name: button160
    command: sensors -u

